Title: taskcat workshop quiz
Author: AWS Quick Start team
Image: https://taskcat.github.io/workshop/images/Taskcat-logo.png
Theme: 282828
Questions:
    Question1:
        Type: Radio
        Label: ""
        Values:
            Value1: "1"
            Value2: "2"
            Value3: "3"
            Value4: "4"
