Title: taskcat workshop quiz
Author: AWS Quick Start team
Image: https://a0.awsstatic.com/main/images/logos/aws_logo_smile_1200x630.png
Theme: 282828
Questions:
    Question1:
        Type: Radio
        Label: ""
        Values:
            Value1: "1"
            Value2: "2"
            Value3: "3"
            Value4: "4"
