project:
  name: cfn-project
tests:
  mytest:
    template: templates/lab3.template.yaml
    regions:
    - us-east-1
    parameters:
      S3BucketName: '$[taskcat_autobucket]'
      S3KeyPrefix: 'cfn-project/'
      LicenseToken: 'MY-FAKE-LICENSE-KEY'
      AvailabilityZones: $[taskcat_genaz_2]
